version: '3'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8844:8844"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8844
      - MCP_PATH=/mcp
      - MCP_LOG_LEVEL=info
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8844/.well-known/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s